windows build: fix build error related to 'plugin_common.h'
This fixes build errors like:
  anonymous.c
  anonymous.c(55) : fatal error C1083: Cannot open include file: 'plugin_common.h': No such file or directory
  anonymous_init.c
  anonymous_init.c(17) : fatal error C1083: Cannot open include file: 'plugin_common.h': No such file or directory
  plugin_common.c
  plugin_common.c(74) : fatal error C1083: Cannot open include file: 'plugin_common.h': No such file or directory

The problem was that rule for 'plugin_common.h' was never executed because
it's not a dependency of anything. While at it, get rid of file copying.
Instead, search for sources in other directories.

Signed-off-by: Alexandr Miloslavskiy <alexandr.miloslavskiy@syntevo.com>