Allow saslauthd to be built outside of source tree while configuring with `--enable-ldapdb'
[snip]
| powerpc-wrs-linux-gcc [snip] -I../common
|../../git/saslauthd/lak.c:58:10: fatal error: crypto-compat.h:
No such file or directory
[snip]

The crypto-compat.h locates in git/common/, it should be                                                                                                                           |
`-I../../git/common'

Remove useless `-I$(top_srcdir)/../include' which was incorrectly
added by commit `faae590 cleanup misc INCLUDES for different build paths'

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>