configure prototypes
  * Set to use function prototypes for ANSI_C
  If PROTOTYPES is set in md5global.h, it uses PROTO_LIST(list) list instead of PROTO_LIST(list) ()
  to provide parameterized prototyping.
  Therefore, at the configure.ac stage, when using ANSI_C, PROTOTYPES should be defined.

  * to fix the build error with gcc-15
    Even though I added this configuration to fix the error, the error shown in the following patch still occurs.
../../git/lib/md5.c:139:8: error: too many arguments to function 'MD5_memcpy'; expected 0, have 3
  139 |        MD5_memcpy
      |        ^~~~~~~~~~
  140 |        ((POINTER)&context->buffer[index], (POINTER)input, partLen); MD5Transform
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../git/lib/md5.c:62:13: note: declared here
   62 | static void MD5_memcpy PROTO_LIST ((POINTER, POINTER, unsigned int));
      |             ^~~~~~~~~~

Signed-off-by: mark.yang <mark.yang@lge.com>