Fix build with --disable-shared --enable-static
1. Rename SASL_STATIC_LIBS to SASL_STATIC_LIB to free up SASL_STATIC_LIBS for
the list of additional libraries needed by static libsasl due to the plugins
that are included in libsasl only in the static build.
2. Add LIB_DES to SASL_STATIC_LIBS for the digestmd5 plugin.
3. Add SASL_DB_LIB to the list of libraries needed by libsasldb.

The second point fixes linking utils/dbconverter-2 which fails with:
ld: ../lib/.libs/libsasl2.a(digestmd5.o): in function `init_3des':
lib/digestmd5.c:968: undefined reference to `DES_key_sched'

The third point fixes linking sample/client which fails with:
ld: ../lib/.libs/libsasl2.a(db_berkeley.o): in function `berkeleydb_open':
lib/db_berkeley.c:103: undefined reference to `db_create'

Signed-off-by: Orivej Desh <orivej@gmx.fr>