windows build: fix errors related to 'gssapi.h'
This commit changed how 'gssapi.h' is located:
  867d70cb by Ken Murchison, 2017-07-13 22:15:12
  Fixed issue #326: sasl2.m4 has broken gssapi logic (patch from Jan Parcel)

Fix Windows build files to follow.
While at it, also use 'gssapi/gssapi_krb5.h' because it's present.

This fixes errors like:
gssapi.c(95) : error C2061: syntax error : identifier 'gss_spnego_oid'

Signed-off-by: Alexandr Miloslavskiy <alexandr.miloslavskiy@syntevo.com>